version: '3'
services:
  coding-challenge-fullstack-frontend:
    image: coding-challenge-fullstack-frontend:latest
    container_name: coding-challenge-fullstack-frontend
    ports:
      - "3000:3000"